/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Product {
  id: number;
  name: string;
  /** @nullable */
  description?: string | null;
  price: number;
  /** @nullable */
  imageUrl?: string | null;
  inStock: boolean;
  createdAt: string;
  /** @nullable */
  updatedAt?: string | null;
}

export interface ProductInput {
  name: string;
  /** @nullable */
  description?: string | null;
  price: number;
  /** @nullable */
  imageUrl?: string | null;
  inStock?: boolean;
}

export interface ProductUpdate {
  name?: string;
  /** @nullable */
  description?: string | null;
  price?: number;
  /** @nullable */
  imageUrl?: string | null;
  inStock?: boolean;
}

export interface Order {
  id: number;
  productId: number;
  productName: string;
  /** @nullable */
  productImageUrl?: string | null;
  firstName: string;
  lastName: string;
  phone: string;
  wilaya: string;
  quantity: number;
  totalPrice: number;
  status: string;
  createdAt: string;
  /** @nullable */
  updatedAt?: string | null;
}

export interface OrderInput {
  productId: number;
  firstName: string;
  lastName: string;
  phone: string;
  wilaya: string;
  quantity: number;
}

export type OrderStatusUpdateStatus =
  (typeof OrderStatusUpdateStatus)[keyof typeof OrderStatusUpdateStatus];

export const OrderStatusUpdateStatus = {
  pending: "pending",
  confirmed: "confirmed",
  shipped: "shipped",
  delivered: "delivered",
  cancelled: "cancelled",
} as const;

export interface OrderStatusUpdate {
  status: OrderStatusUpdateStatus;
}

export interface AdminCredentials {
  username: string;
  password: string;
}

export interface AdminUser {
  username: string;
}

export interface LogoutResult {
  success: boolean;
}

export interface AdminStats {
  totalProducts: number;
  totalOrders: number;
  pendingOrders: number;
  totalRevenue: number;
}
